try new slack code

diff --git a/.github/workflows/open-slack-channel.yaml b/.github/workflows/open-slack-channel.yaml
--- a/.github/workflows/open-slack-channel.yaml
+++ b/.github/workflows/open-slack-channel.yaml
@@ -10,8 +10,29 @@ on:
 jobs:
   open-slack-channel:
     runs-on: ubuntu-latest
+    env:
+      PD_INCIDENT_ID: ${{ fromJson(inputs.port_payload).event.diff.after.identifier }}
+      PD_INCIDENT_URL: ${{ fromJson(inputs.port_payload).event.diff.after.properties.url }}
+      PORT_INCIDENT_URL: https://app.getport.io/pagerdutyIncidentEntity?identifier=${{ fromJson(inputs.port_payload).event.diff.after.identifier }}
 
     steps:
+      - uses: actions/checkout@v4
+
+      - name: Log Github Issue Creation
+        uses: port-labs/port-github-action@v1
+        with:
+          clientId: ${{ secrets.PORT_CLIENT_ID }}
+          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
+          baseUrl: https://api.getport.io
+          operation: PATCH_RUN
+          runId: ${{ fromJson(github.event.inputs.port_payload).run.id }}
+          logMessage: "Creating a new Github issue for this incident..."
+
+      - uses: JasonEtco/create-an-issue@v2
+        id: create-github-issue
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
       - name: Log Executing Request to Open Channel
         uses: port-labs/port-github-action@v1
         with:
@@ -20,27 +41,47 @@ jobs:
           baseUrl: https://api.getport.io
           operation: PATCH_RUN
           runId: ${{ fromJson(github.event.inputs.port_payload).run.id }}
-          logMessage: "About to create a conversation channel in slack..."
+          logMessage: | 
+            Github issue created successfully: ${{ steps.create-github-issue.outputs.url }}
+
+            Creating a new Slack channel for this incident...
 
       - name: Create Slack Channel
         id: create_channel
         env:
           SLACK_TOKEN: ${{ secrets.BOT_USER_OAUTH_TOKEN }}
         run: |
-          response=$(curl -s -X POST "https://slack.com/api/conversations.create"             -H "Authorization: Bearer $SLACK_TOKEN"             -H "Content-Type: application/json"             --data "{\"name\": \"incident-${{ fromJson(github.event.inputs.port_payload).event.diff.after.identifier }}\",\"is_private\": false }")
-          echo "API Response: $response"
-          if [[ "$(echo $response | jq -r '.ok')" == "true" ]]; then
+          response=$(curl -s -X POST "https://slack.com/api/conversations.create" \
+            -H "Authorization: Bearer ${SLACK_TOKEN}" \
+            -H "Content-Type: application/json" \
+            -d "{\"name\":\"$CHANNEL_NAME\"}")
+        
+          # Check if the channel was created successfully
+          ok=$(echo $response | jq -r '.ok')
+          
+          if [ "$ok" == "true" ]; then
+            echo "Channel '$CHANNEL_NAME' created successfully."
             channel_id=$(echo $response | jq -r '.channel.id')
-            echo "Channel ID: $channel_id"
-            echo "CHANNEL_ID=$channel_id" >> $GITHUB_ENV
+            echo "SLACK_CHANNEL_URL="https://slack.com/app_redirect?channel=$channel_id" >> GITHUB_OUTPUT
           else
-            echo "Failed to create Slack channel. Channel ID is null."
             error=$(echo $response | jq -r '.error')
-            error_message="${error//_/ }"
-            echo "Error: $error_message"
-            echo "CREATE_CHANNEL_ERROR=$error_message" >> $GITHUB_ENV
-            exit 1
+            echo "Error creating channel: $error"
           fi
+
+          # response=$(curl -s -X POST "https://slack.com/api/conversations.create"             -H "Authorization: Bearer $SLACK_TOKEN"             -H "Content-Type: application/json"             --data "{\"name\": \"incident-${{ fromJson(github.event.inputs.port_payload).event.diff.after.identifier }}\",\"is_private\": false }")
+          # echo "API Response: $response"
+          # if [[ "$(echo $response | jq -r '.ok')" == "true" ]]; then
+          #   channel_id=$(echo $response | jq -r '.channel.id')
+          #   echo "Channel ID: $channel_id"
+          #   echo "CHANNEL_ID=$channel_id" >> $GITHUB_ENV
+          # else
+          #   echo "Failed to create Slack channel. Channel ID is null."
+          #   error=$(echo $response | jq -r '.error')
+          #   error_message="${error//_/ }"
+          #   echo "Error: $error_message"
+          #   echo "CREATE_CHANNEL_ERROR=$error_message" >> $GITHUB_ENV
+          #   exit 1
+          # fi
 
       - name: Log If Create Channel Request Fails
         if: failure()
