added get id by email for slack members

diff --git a/.github/workflows/open-slack-channel.yaml b/.github/workflows/open-slack-channel.yaml
--- a/.github/workflows/open-slack-channel.yaml
+++ b/.github/workflows/open-slack-channel.yaml
@@ -117,10 +117,21 @@ jobs:
         run: |
           members=('matar@getport.io' 'zohar@getport.io' 'bogu@getport.io' 'matanheled@getport.io')
           for member in "${members[@]}"; do
+            user_response=$(curl -s -X GET "https://slack.com/api/users.lookupByEmail?email=$email" \
+              -H "Authorization: Bearer $SLACK_TOKEN")
+
+            if [[ "$(echo $user_response | jq -r '.ok')" == "true" ]]; then
+              user_id=$(echo $user_response | jq -r '.user.id')
+            else
+              error_message="Failed to retrieve user id for $email: $(echo $user_response | jq -r '.error' | tr '_' ' ') ⚠️"
+              report_error "$error_message"
+              exit 1
+            fi
+
             add_user_response=$(curl -s -X POST "https://slack.com/api/conversations.invite" \
                 -H "Authorization: Bearer $SLACK_TOKEN" \
                 -H "Content-Type: application/json" \
-                -d "{\"channel\":\"$CHANNEL_ID\", \"users\":\"$member\"}")
+                -d "{\"channel\":\"$CHANNEL_ID\", \"users\":\"$user_id\"}")
             
             user_ok=$(echo $add_user_response | jq -r '.ok')
             if [ "$user_ok" == "true" ]; then
